kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: sparkclusters.radanalytics.io
spec:
  group: radanalytics.io
  names:
    kind: SparkCluster
    listKind: SparkClusterList
    plural: sparkclusters
    singular: sparkcluster
  scope: Namespaced
  version: v1
  additionalPrinterColumns:
  - name: Workers
    type: string
    description: The number of workers in the Spark cluster
    JSONPath: .spec.worker.instances
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
