repos:
  - repo: local
    hooks:
      - id: format-python
        name: Format Python code
        entry: ./dev/reformat-python
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff
        name: Lint Python code with Ruff
        entry: ./dev/lint-python --ruff
        language: system
        types: [python]
        pass_filenames: false
