apiVersion: radanalytics.io/v1
kind: SparkApplication
metadata:
  name: my-spark-app
spec:
  image: quay.io/jkremser/openshift-spark:2.3-latest
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar
  mainClass: org.apache.spark.examples.SparkPi
  sleep: 300 # repeat each 5 minutes
  driver:
    cores: 0.2
    coreLimit: 200m
  executor:
    instances: 2
    cores: 1
    coreLimit: 400m
  labels:
    foo: bar
