# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: "Build Images"
on:
  workflow_run:
    workflows: ["CI Build"]
    types: ['requested']

env:
  MOUNT_LOCAL_SOURCES: "false"
  MOUNT_FILES: "true"
  FORCE_ANSWER_TO_QUESTIONS: "yes"
  FORCE_PULL_IMAGES: "true"
  CHECK_IMAGE_FOR_REBUILD: "true"
  SKIP_CHECK_REMOTE_IMAGE: "true"
  DB_RESET: "true"
  VERBOSE: "true"
  UPGRADE_TO_LATEST_CONSTRAINTS: false
  PYTHON_MAJOR_MINOR_VERSION: 3.6
  USE_GITHUB_REGISTRY: "true"
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REGISTRY_PULL_IMAGE_TAG: "latest"
  GITHUB_REGISTRY_WAIT_FOR_IMAGE: "false"

jobs:

  cancel-workflow-runs:
    timeout-minutes: 10
    name: "Cancel workflow runs"
    runs-on: ubuntu-latest
    outputs:
      sourceHeadRepo: ${{ steps.cancel.outputs.sourceHeadRepo }}
      sourceHeadBranch: ${{ steps.cancel.outputs.sourceHeadBranch }}
      sourceHeadSha: ${{ steps.cancel.outputs.sourceHeadSha }}
      sourceEvent: ${{ steps.cancel.outputs.sourceEvent }}
      cacheDirective: ${{ steps.cache-directive.outputs.docker-cache }}
    steps:
      - name: "Cancel duplicated 'CI Build' runs"
        uses: potiuk/cancel-workflow-runs@v2
        id: cancel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: duplicates
          sourceRunId: ${{ github.event.workflow_run.id }}
      - name: "Cancel duplicated 'Build Image' runs"

        # We find duplicates of our own "Build Image" runs - due to a missing feature
        # in GitHub Actions, we have to use Job names to match Event/Repo/Branch from the
        # build-info step there to find the duplicates ¯\_(ツ)_/¯.

        uses: potiuk/cancel-workflow-runs@v2
        with:
          cancelMode: namedJobs
          token: ${{ secrets.GITHUB_TOKEN }}
          jobNameRegexps: >
            [".*Event: ${{ steps.cancel.outputs.sourceEvent }}
            Repo: ${{ steps.cancel.outputs.sourceHeadRepo }}
            Branch: ${{ steps.cancel.outputs.sourceHeadBranch }}.*"]
      - name: "Cancel all 'CI Build' runs where some jobs failed"

        # We find any of the "CI Build" workflow runs, where any of the important jobs
        # failed. The important jobs are selected by the regexp array below.
        # We also produce list of canceled "CI Build' runs as output, so that we
        # can cancel all the matching "Build Images" workflow runs in the two following steps.
        # Yeah. Adding to the complexity ¯\_(ツ)_/¯.

        uses: potiuk/cancel-workflow-runs@v2
        id: cancel-failed
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: failedJobs
          sourceRunId: ${{ github.event.workflow_run.id }}
          jobNameRegexps: >
            ["^Static checks.*", "^Build docs$", "^Spell check docs$", "^Backport packages$",
             "^Checks: Helm tests$", "^Test OpenAPI*"]
      - name: "Extract canceled failed runs"

        # We use this step to build regexp that will be used to match the Source Run id in
        # the build-info job below. If we cancelled some "CI Build" runs in the "cancel-failed' step
        # above - we want to cancel also the corresponding "Build Images" runs. Again we have
        # to match the jobs using job name rather than use proper API because that feature
        # is currently missing in GitHub Actions ¯\_(ツ)_/¯.

        id: extract-cancelled-failed-runs
        if: steps.cancel-failed.outputs.cancelledRuns != '[]'
        run: |
            REGEXP="Source Run id: "
            SEPARATOR=""
            for run_id in $(echo "${{ steps.cancel-failed.outputs.cancelledRuns }}" | jq '.[]')
            do
                REGEXP="${REGEXP}${SEPARATOR}(${run_id})"
                SEPARATOR="|"
            done
            echo "::set-output name=matching-regexp::[\"${REGEXP}\"]"
      - name: "Cancel triggered 'Build Images' runs for the cancelled failed runs"

        # In case we do have some cancelled jobs in the "cancel-failed" step above
        # We take the extracted regexp array prepared in the previous step and we use
        # it to cancel any jobs that have matching names containing Source Run Id:
        # followed by one of the run ids. Yes I know it's super complex ¯\_(ツ)_/¯.

        if: steps.cancel-failed.outputs.cancelledRuns != '[]'
        uses: potiuk/cancel-workflow-runs@v2
        with:
          cancelMode: namedJobs
          token: ${{ secrets.GITHUB_TOKEN }}
          jobNameRegexps: ${{ steps.extract-cancelled-failed-runs.outputs.matching-regexp }}
      - name: "Set Docker Cache Directive"
        id: cache-directive
        run: |
          if [[ ${{ steps.cancel.outputs.sourceEvent }} == "schedule" ]]; then
              echo "::set-output name=docker-cache::disabled"
          else
              echo "::set-output name=docker-cache::pulled"
          fi

  build-info:
    # The name is such long because we are using it to cancel duplicated 'Build Images' runs
    # by matching Event/Repo/Branch. This is a workaround for a missing feature of GitHub
    # Actions to link the source workflow run and the triggered workflow_run one.
    # We are also cancelling SourceRunId in case we determine that we should cancel the source
    # Run because of some failing jobs in the source run. Again ¯\_(ツ)_/¯.
    name: >
      Event: ${{ needs.cancel-workflow-runs.outputs.sourceEvent }}
      Repo: ${{ needs.cancel-workflow-runs.outputs.sourceHeadRepo }}
      Branch: ${{ needs.cancel-workflow-runs.outputs.sourceHeadBranch }}
      Run id: ${{ github.run_id }}
      Source Run id: ${{ github.event.workflow_run.id }}
      Sha: ${{ github.sha }}
      Source Sha: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
    runs-on: ubuntu-latest
    needs: [cancel-workflow-runs]
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: >
          Event: ${{ needs.cancel-workflow-runs.outputs.sourceEvent }}
          Repo: ${{ needs.cancel-workflow-runs.outputs.sourceHeadRepo }}
          Branch: ${{ needs.cancel-workflow-runs.outputs.sourceHeadBranch }}
          Run id: ${{ github.run_id }}
          Source Run id: ${{ github.event.workflow_run.id }}
          Sha: ${{ github.sha }}
          Source Sha: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
        run: |
          printenv

  build-images:
    timeout-minutes: 80
    name: "Build ${{matrix.image-type}} images ${{matrix.python-version}}"
    runs-on: ubuntu-latest
    needs: [cancel-workflow-runs]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        image-type: [CI, PROD]
      fail-fast: true
    env:
      BACKEND: postgres
      PYTHON_MAJOR_MINOR_VERSION: ${{ matrix.python-version }}
      GITHUB_REGISTRY_PUSH_IMAGE_TAG: ${{ github.event.workflow_run.id }}
      UPGRADE_TO_LATEST_CONSTRAINTS: >
        ${{ needs.cancel-workflow-runs.outputs.sourceEvent == 'push' ||
        needs.cancel-workflow-runs.outputs.sourceEvent == 'scheduled' }}
      DOCKER_CACHE: ${{ needs.cancel-workflow-runs.outputs.cacheDirective }}
    steps:
      - name: >
          Checkout [${{ needs.cancel-workflow-runs.outputs.sourceEvent }}]
          Event: ${{ needs.cancel-workflow-runs.outputs.sourceEvent }}
          Repo: ${{ needs.cancel-workflow-runs.outputs.sourceHeadRepo }}
          Branch: ${{ needs.cancel-workflow-runs.outputs.sourceHeadBranch }}
          Run id: ${{ github.run_id }}
          Source Run id: ${{ github.event.workflow_run.id }}
          Sha: ${{ github.sha }}
          Source Sha: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.cancel-workflow-runs.outputs.sourceHeadSha }}
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} ) to 'main-airflow' to use main scripts"
        uses: actions/checkout@v2
        with:
          path: "main-airflow"
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: "Override 'scripts/ci' with the ${{ github.ref }} version so that the PR cannot override it."
        # We should not override those scripts which become part of the image as they will not be
        # changed in the image built - we should only override those that are executed to build
        # the image.
        run: |
          rm -rf "scripts/ci"
          mv "main-airflow/scripts/ci" "scripts"
      - name: "Free space"
        run: ./scripts/ci/tools/ci_free_space_on_ci.sh
      - name: "Build CI images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
        run: ./scripts/ci/images/ci_prepare_ci_image_on_ci.sh
        if: matrix.image-type == 'CI'
      - name: "Push CI images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
        run: ./scripts/ci/images/ci_push_ci_images.sh
        if: matrix.image-type == 'CI'
      - name: "Build PROD images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
        run: ./scripts/ci/images/ci_prepare_prod_image_on_ci.sh
        if: matrix.image-type == 'PROD'
      - name: "Push PROD images ${{ matrix.python-version }}:${{ github.event.workflow_run.id }}"
        run: ./scripts/ci/images/ci_push_production_images.sh
        if: matrix.image-type == 'PROD'
      - name: "Canceling the CI Build source workflow in case of failure!"
        if: cancelled() || failure()
        uses: potiuk/cancel-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: self
          sourceRunId: ${{ github.event.workflow_run.id }}
